### ISSUE TITLE
Should the Controller Document specification be in scope for the revised charter?

### ISSUE THREAD

**Issue by thereisnogabe** [w3c/vc-wg-charter#115]
https://w3c.github.io/vc-controller-document/

With the securing mechanism specs in this group's charter in CR it seems like the right time to move shared language to the controller document spec, if the group is still interested in that path. I believe it's a useful spec to have.

cc: @selfissued @msporny

**Comment by selfissued** [comment]
Agreed that it's time to work on the Controller Document spec and that it should be in scope for our charter.

**Comment by iherman** [comment]
(I have no strong opinion as for the controller document itself. My comment is exclusively on the chartering aspects.)

@decentralgabe, 

Imho, this change would completely change the dynamics of this rechartering. The [controller document]([https://w3c.github.io/vc-controller-document/](https://w3c.github.io/vc-controller-document/)) is not even a Working Draft for the moment. 

This means there is no way we could finish it as a Recommendation at the same time as the others (i.e., at the prospected date of January 2025). I.e., we cannot really add it to the [Deliverables section](https://w3c.github.io/vc-wg-charter/#deliverables) without further ado. In other words, the current goal of the charter renewal, namely to give us extra time to finish the current work and then become a maintenance Working Group, would go away. We would be engaging into a full-blown rechartering process, with new deliverables; this is a different dynamics both vis-a-vis the AC as well as ourselves. This would unavoidably lead to a major re-write of the charter (why stop at the controller document, after all)?

That is, of course, perfectly doable in theory. But, socially, I do not think we are ready to have this discussion ***now***. The work ahead of us to properly finish the 8 Recommendations is already a tall order, and I do not believe we can ask the WG members to spend their time on that work _as well_.

Let me repeat what I wrote in my comment in https://github.com/w3c/vc-wg-charter/issues/114#issuecomment-2072989895:

> Once all Recommendations are published (hopefully Jan 2025), the WG will have time to conduct a relaxed discussion on where to go after this. We may even decide to start this discussion earlier (e.g., at TPAC) without any time pressure on us. A new charter can then be completely re-worked, new items added, etc.; we can plan to do so once the current work load disappears. We are not required to wait until the end of the 2 years to recharter; we can decide, _at any time_, to do so.

My preference is, therefore, to keep things to the absolute minimal level _for now_, which would, hopefully, go through the AC vote without many issues, and consider a new charter once we are out of the woods.

**Comment by thereisnogabe** [comment]
Ok, that is reasonable. I would welcome @msporny's input and maybe something to discuss on the next call before we come to a conclusion. Is there an intermediary step we can take to progress the document while not having it interfere with the charter?

**Comment by iherman** [comment]
With the recent evolution around the controller document, as soon as that document is published as a FPWD I can (and should) add it to the list of inherited  rec-track documents. I presume this makes this issue moot.

**Comment by thereisnogabe** [comment]
agreed @iherman
