### ISSUE TITLE
Standardizing PGP for Linked Data Integrity

### ISSUE THREAD

**Issue by OR13** [w3c/vc-wg-charter#48]
https://w3id.org/security/suites/pgp-2021
https://w3id.org/security/suites/pgp-2021/v1

PGP / GPG are commonly used in software supply chain uses cases, and even in hardware thanks to [Yubikey / Open PGP](https://support.yubico.com/hc/en-us/articles/360013790259-Using-Your-YubiKey-with-OpenPGP).

GitHub integrations with [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account)

[Signing Docker images with GPG](https://www.unboundsecurity.com/docs/UKC/UKC_Code_Signing_IG/HTML/Content/Products/UKC-EKM/UKC_Code_Signing_IG/GPG/GPGdocker.htm)

While PGP won't play nice with VC-JWT, it can play nice with LD Proofs, as shown the specs at the top of this issue.

You can even use GPG Agent to create verifiable credentials that are bound to hardware isolated keys (such as with yubikey).

Is there interest in standardizing support for PGP / GPG based Linked Data Integrity suites?

**Comment by mprorock** [comment]
Absolutely.  This could be highly valuable to us

**Comment by OR13** [comment]
Here is an example CLI that works with these suites, https://github.com/OR13/lds-pgp2021/blob/main/bin/cli.js

it uses GPGAgent and Yubikey, and allows you to make a verifiable credential that is signed by a hardware isolated key on yubikey but verifiable to any DID that supports PGP. (or in the context of VCs any controller).

**Comment by OR13** [comment]
Open PGP supports most of the cryptography that is popular these days.

Checkout https://openpgpjs.org/

> This project is maintained by ProtonMail.

https://github.com/openpgpjs/openpgpjs

See also: https://github.com/openpgpjs/openpgpjs#security-audit

**Comment by wyc** [comment]
+1, we are supporting PGP keys as well:
https://github.com/spruceid/ssi/pull/373

**Comment by brentzundel** [comment]
I believe that merging PR #77 will fix this issue

**Comment by brentzundel** [comment]
I believe this issue has been addressed. Marking as pending close.
I will close this issue in 4 days if there are no objections.

**Comment by brentzundel** [comment]
no response since marked `pending close`, closing
