### ISSUE TITLE
expand acronyms on first use

### ISSUE THREAD

**Issue by samuelweiler** [w3c/vc-wg-charter#53]
The example that jumped out is DLT.  Also JWP / VC-JWP.

This is request is modeled on https://www.rfc-editor.org/rfc/rfc7322.html#section-3.6

**Comment by iherman** [comment]
I understand the issue, but I am a bit worried about the effect on readability of sections like the one on the Verifiable Credential Data Integrity deliverable (I guess that is where you found most of them). Would it be an alternative to have a separate "glossary" section either in the charter text itself, or put it into a separate file that can be linked from the charter text itself. WDYT?

**Comment by samuelweiler** [comment]
It's possible that the addressing of https://github.com/w3c/vc-wg-charter/issues/59 will cover most of this, since the first use of the terms will be in the background section with explanatory words wrapped gently around them.  

A glossary is not a great solution.  I want the charter to be understandable by corners of our community that aren't steeped in the VC world - namely (most of) our AC reps.  Flipping back and forth isn't great - the text should stand on its own.  If a glossary is needed, put it at the beginning of the doc.

**Comment by iherman** [comment]
Beginning of the document is fine with me, too. But let us wait until #59 is closed.

**Comment by Sakurann** [comment]
@iherman I think it is ok to have `JSON Web Proofs (JWP)` kind of clarifications in the charter text. Should not impact readability too much. Happy to do a PR once we agree on the text in the data integrity simplification PR.

**Comment by iherman** [comment]
> @iherman I think it is ok to have `JSON Web Proofs (JWP)` kind of clarifications in the charter text. Should not impact readability too much. Happy to do a PR once we agree on the text in the data integrity simplification PR.

I agree that we should come back to this issue when the bulk of the (possibly fairly complex) issues are closed. Until then, this issue remains open...

**Comment by brentzundel** [comment]
@samuelweiler, @Sakurann, and @iherman I have created PR #79 to address this issue, which will be closed if that PR is merged.
