### ISSUE TITLE
Update the Verifiable Credential Data Integrity 1.0 section

### ISSUE THREAD

**Issue by OR13** [w3c/vc-wg-charter#54]
The entire section needs to be rewritten to communicate layers in a less ambiguous manner and cite references respectfully.

As the sole author of the following:

- [Ecdsa Secp256k1 Signature 2019](https://w3c-ccg.github.io/lds-ecdsa-secp256k1-2019/)
- [Ed25519 Signature 2020](https://w3c-ccg.github.io/lds-ed25519-2020/)

Co-editor / author of:

- [BBS+ Signatures 2020](https://w3c-ccg.github.io/ldp-bbs2020/)

Contributor to:

- [draft-jmiller-json-proof-token](https://json-web-proofs.github.io/json-web-proofs/)

I find the "rebranding" of the work items completely unacceptable.

The work items MUST be referred to by the names that they are currently using, anything else is unacceptable.

Additionally, there is a harmful ambiguity that is being perpetuated by this section which is conflating "Data Integrity" with "cryptographic serializations" with "raw cryptographic primitives".

I think its fine to refer to each layer in this section, but 100% not acceptable to "group everything together as if these are the same things".

Our charter forbids us from doing "raw cryptographic primitives", yet we can refer to work happening elsewhere.

Our charter grants us the ability to do "cryptographic serializations", but what we do here and what we happens elsewhere MUST be clearly and cleanly separated in unambiguous language.

Our charter grants use the ability to do "Data Integrity", but not to define "one ring to rule them all" form of it... We need to clearly communicate how this section will account for supporting decentralization and diversity.

**Comment by selfissued** [comment]
> I find the "rebranding" of the work items completely unacceptable.

I completely agree with this.  References to all referenced specifications must use the accurate titles for these specifications.

**Comment by bumblefudge** [comment]
Uh oh, apologies if my PR contributed to this.  Go easy on the new guy!

**Comment by brentzundel** [comment]
@OR13 am I correct in assuming that this issue may be closed if PR #77 is merged?

**Comment by brentzundel** [comment]
I believe this issue has been addressed. Marking as `pending close`.
I will close this issue in 4 days if there are no objections.

**Comment by brentzundel** [comment]
no response since marked `pending close`, closing
