### ISSUE TITLE
Add charter history

### ISSUE THREAD

**Issue by samuelweiler** [w3c/vc-wg-charter#55]
The charter lacks a history section or changelog, e.g. highlighting the move from maintenance mode back into a more active mode.

**Comment by iherman** [comment]
@samuelweiler there is a PR (#49) that, in general, aligns the charter with the latest version of the charter template and this includes a history table. Can you look at that one and, possibly, comment there? Thx.

**Comment by samuelweiler** [comment]
I prefer to see a history table that goes back to the beginning of the WG - something that shows the initial charter, the recharter into maintenance mode, and anything in between.  The line for this recharter would name the new deliverables and summarize, **very** briefly, the change in scope.

**Comment by iherman** [comment]
Do you mean copy the whole of https://www.w3.org/2020/12/verifiable-credentials-wg-charter.html#about into this charter (with an additional line that is there)? I am fine with this, but I am a bit afraid it is a little bit over the top...
