### ISSUE TITLE
Draft state for Verifiable Credential Data Integrity 1.0?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/vc-wg-charter#56]
The entry under "draft state" for Verifiable Credential Data Integrity 1.0 doesn't make sense on its own.

**Comment by iherman** [comment]
@samuelweiler this comes from the charter template of the strategy team... and I agree it does not make too much sense in this case. Would it be acceptable to say 'Input documents' as opposed to 'Draft state'?

**Comment by samuelweiler** [comment]
Will one or more of the listed drafts be replaced by this new doc?  e.g. the community group report?  https://w3c-ccg.github.io/data-integrity-spec/. If so, many answer the questions for that doc or those docs?  Otherwise, if the other docs will stand alone and this will be a new one, the state might be "no draft"?

**Comment by iherman** [comment]
@samuelweiler this WG has no formal influence on what the CCG will do or not do. That is why I proposed to replace the 'draft state' header to 'input documents'.

**Comment by samuelweiler** [comment]
Got it.  Then I think "no draft" is the state.  (That is one of the options in the template!)  And you can clarify that the other docs will be used as inputs.

**Comment by OR13** [comment]
related https://github.com/w3c/vc-wg-charter/issues/54

**Comment by OR13** [comment]
I see them all as input documents, with the assumption that nothing done in a CG must be preserved, in other words the WG is not obligated to retain any normative language from a community group draft.

Does that align with your understanding regarding links to W3C CCG documents (or really any other input documents)?

**Comment by brentzundel** [comment]
PR #76 includes a change to the draft status of the VCDI deliverable as recommended by the comments in this issue.

**Comment by brentzundel** [comment]
PR #76 has been merged. I am marking this issue as `pending close` as I believe it has been addressed.

It will be closed in 7 days if there are no objections.

**Comment by brentzundel** [comment]
no comments since marked pending closed, closing
