### ISSUE TITLE
Data model or models

### ISSUE THREAD

**Issue by samuelweiler** [w3c/vc-wg-charter#57]
I see a work item of a data model (singular) with words in the scope section about data models (plural).  What other data models are in scope?

**Comment by iherman** [comment]
Good point. 

@brentzundel @Sakurann @msporny: In my understanding, we have a _single_ data model for credentials that has 'sub parts' listed in the scope. This needs reformulation...

**Comment by brentzundel** [comment]
@samuelweiler PR #60 has been merged, please let us know if these changes address this issue to your satisfaction.

**Comment by brentzundel** [comment]
This issue has been addressed by PR #60 and will be closed soon if no objection to doing so is raised.

**Comment by brentzundel** [comment]
no comments since marked pending closed, closing
