### ISSUE TITLE
Success criteria ???

### ISSUE THREAD

**Issue by samuelweiler** [w3c/vc-wg-charter#58]
> The group will there ....

It looks like you rewrote the [boilerplate from the charter template](https://w3c.github.io/charter-drafts/charter-template.html).

Whenever that happens, I wonder why we're not seeing a PR back to the template - if the template needs to be improved, let's improve it. 

Meanwhile, the rewrite is ungrammatical.

**Comment by iherman** [comment]
@samuelweiler, coincidentally, I synced with the latest template (including the success criteria section) a few days ago, see #49. Could you look at, and comment, on that PR to see if it is o.k.?

For the specifics: that PR took over the boiler-plate section for the success criteria recently, see https://github.com/w3c/vc-wg-charter/pull/49#discussion_r793259239

**Comment by samuelweiler** [comment]
#49 fixes this issue.
