### ISSUE TITLE
More narrative description/ background

### ISSUE THREAD

**Issue by samuelweiler** [w3c/vc-wg-charter#59]
There are some words in the scope section, namely "presentations" and "proofs" that don't make much sense on their own, and there is not sufficient background text here to understand them.  Perhaps adding a background section/discussion as an intro to the charter would help?

I'm marking this one -needs-resolution because it's about explaining the substance.

**Comment by brentzundel** [comment]
my first inclination was to grab the text from [the VC Data Model Introduction](https://www.w3.org/TR/vc-data-model/#introduction) and paste it into the charter, but I worry that may be overkill. Would linking to that section from the charter be sufficient to address this issue @samuelweiler ?

**Comment by brentzundel** [comment]
PR #75 has been raised to address this issue. @samuelweiler please let us know if this PR addresses this issue to your satisfaction.

**Comment by brentzundel** [comment]
PR #75 has been merged. I am marking this issue as `pending close` as I believe it has been addressed.

It will be closed in 7 days if there are no objections.

**Comment by brentzundel** [comment]
no comments since marked pending closed, closing
