### ISSUE TITLE
Clarification on supported proof types

### ISSUE THREAD

**Issue by awoie** [w3c/vc-wg-charter#78]
The charter currently says:
> Concrete serializations will be provided based on [VC-JWT](https://w3c.github.io/vc-data-model/#json-web-token), the [Ed25519 Cryptosuite](https://w3c-ccg.github.io/lds-ed25519-2020/), the [Secp256k1 Cryptosuite](https://w3c-ccg.github.io/lds-ecdsa-secp256k1-2019/), and for [JSON Web Signature 2020](https://github.com/w3c-ccg/lds-jws2020/). Concrete serializations based on the [BBS+ Cryptosuite](https://w3c-ccg.github.io/ldp-bbs2020/) might be provided, if an [IETF BBS+ RFC](https://identity.foundation/bbs-signature/) is published in time.

I just want to make sure that this is not an exhaustive list and other proof types might be supported (even though they won't be standardised under this charter). We should probably add some language to the charter that clarifies that the above ^^ are concrete examples for proof types and their serializations but other are considered valid as well.

**Comment by brentzundel** [comment]
The VCDI deliverable description is quite different now that a few PRs have been merged.
After review of the current language, do you still feel there is an issue that may be resolved with changes to the charter text?

**Comment by kdenhartog** [comment]
It's worth pointing out that even if things are not standardized under this charter I believe there's an understanding that additional proof suites can be defined and registered under the extension registry as well

**Comment by brentzundel** [comment]
@awoie I believe this issue will be addressed in PR #85, do you agree?

**Comment by awoie** [comment]
I just want to make sure that the charter itself does not say all allowed verification methods / proofs will be produced by the working group and I want to make sure the charter still allows room for innovation through a registry (process). So I guess the PR #85 should address this.

**Comment by Sakurann** [comment]
Current charter states as follows (emphasis are mine). Will this address your concerns (that I agree with)? 

> This family of specifications consists of documents that each define how to express proofs of integrity for verifiable credentials using a number of concrete serializations for each of the defined syntaxes. The specific set of concrete serializations included will be determined by the Working Group. **The following are a non-exhaustive selection of expected input documents:**
> - Container Formats: VC-JSON Web Token (JWT), Data Integrity
> - Cryptosuites: JSON Web Signature 2020, EdDSA, NIST ECDSA, Koblitz ECDSA

**Comment by brentzundel** [comment]
The associated PRs which reflect the consensus of the group (and lack thereof) have been either merged or closed. Closing this Issue.
